### ISSUE TITLE
Read file by ReaderCloser

### ISSUE THREAD

**Issue by nicola-spb** [actforgood/bigcsvreader#11]
**Describe the problem this feature is intended for**
I have csv file in archive and file has not real path. How can I read this file by io.ReaderCloser?

**Describe the solution you'd like**
Please add reading file from io.ReadCloser

**Comment by bogcon** [comment]
Hi @nicola-spb 
Thanks for submitting this enhancement.

Unfortunately, `io.ReadCloser` would not be sufficient for this package to do the parallelization.
This package allocates a number of bytes to multiple goroutines to handle them, so it needs to know the initial size of the file (switching directly to a Reader would mean to perform a reading until `io.EOF` and count the read bytes, which is extra work, but still doable) and also it needs for that reader to implement `io.Seeker` in order for each goroutine to "jumb" to its allocated start offset, so basically it needs a [io.ReadSeekCloser](https://pkg.go.dev/io#ReadSeekCloser),  thus `io.ReadCloser` would not be sufficient.

I would recommend for you to perform the extra work separately, like unarchiving the file in `/tmp` for example, process it with what current implementation offers, and delete the file at the end.

**Comment by nicola-spb** [comment]
Yes. I read your code and found Seek() too.

Archive too big. I searched alternative of std "encoding/csv". But not found.

Ok. Thank you
