### ISSUE TITLE
Reading directory of Multiple CSV files with same Template

### ISSUE THREAD

**Issue by kavin-bytive** [actforgood/bigcsvreader#3]
**Describe the problem this feature is intended for**
I have around 6 tb of csv files, in a directory which i have to process and move to Elastic Search, if this pacakge can support reading a directoy we dont have to run the script again and again

]

 
Thank you for taking the time to request this feature!  
By submitting it, you consent to comply with the [Code of Conduct](https://raw.githubusercontent.com/actforgood/.github/main/CODE_OF_CONDUCT.md).

**Comment by bogcon** [comment]
I don't feel like this should be part of this package, seems like a customization.
This should be part of application logic.
You can list the directory files and read an process each of the file (maybe even in parallel)
This is a pseudocode:
```
files = dir. ListFiles()
foreach file in files {
    readAndProcessFile(file) 
}
```
